/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package libros.de.iva;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jxl.write.WriteException;

/**
 *
 * @author agus
 */
public class VentanaCompras extends javax.swing.JFrame {
    private int contadorFilas=0;
    private ConjuntoCompras compras= new ConjuntoCompras();
    private InformeCompras info = new InformeCompras();
    /**
     * Creates new form VentanaCompras
     */
    public VentanaCompras() {
        initComponents();
        File f = new File ("Ayuda/Ayuda - Compras.html");
                FileReader fr = null;
            try {
                fr = new FileReader(f);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VentanaListaClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedReader br=new BufferedReader(fr);
            String st="";
                    try {
                        int a = Txt.count(f);
                        int b = 0;
                        while(b!=a){
                            a-=1;
                            st = st + br.readLine();
                        }
                        txtPaneAyuda.setText(st);
                    } catch (IOException ex) {
                        Logger.getLogger(VentanaListaClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
//Abro el archivo ListaDeClientes para colocar cada cliente en el combobox
        f = new File ("ListaDeClientes.txt");
                fr = null;
            try {
                fr = new FileReader(f);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VentanaListaClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
            br=new BufferedReader(fr);
            st="";
                    try {
                        int a = Txt.count(f);
                        int b = 0;
                        while(b!=a){
                            a-=1;
                            st = br.readLine();
                            cmbxListaClientes.addItem(st);
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(VentanaListaClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblDiaEmision = new javax.swing.JLabel();
        txtDiaEmision = new javax.swing.JTextField();
        lblFechaEmision = new javax.swing.JLabel();
        lblMesEmision = new javax.swing.JLabel();
        txtMesEmision = new javax.swing.JTextField();
        lblAñoEmision = new javax.swing.JLabel();
        txtAñoEmision = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTipoNroComprobante = new javax.swing.JLabel();
        lblTipoComprobante = new javax.swing.JLabel();
        comboBoxTipoComprobante = new javax.swing.JComboBox();
        lblFiltroTipoComprobante = new javax.swing.JLabel();
        comboBoxFiltroTipo = new javax.swing.JComboBox();
        lblNroComprobante = new javax.swing.JLabel();
        txtNroComprobante = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblComprador = new javax.swing.JLabel();
        lblNombreVendedor = new javax.swing.JLabel();
        txtNombreVendedor = new javax.swing.JTextField();
        lblCUITVendedor = new javax.swing.JLabel();
        txtCUITVendedor = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtImporteTotIVA = new javax.swing.JTextField();
        lblImporteTotIVA = new javax.swing.JLabel();
        lblImporteTotcIVA = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        lblConceptoImpNoNetoGravado = new javax.swing.JLabel();
        txtConceptoImpNoNetoGravado = new javax.swing.JTextField();
        lblImporteNoNetoGravado = new javax.swing.JLabel();
        lblImporteImpNoNetoGravado = new javax.swing.JLabel();
        txtImporteImpNoNetoGravado = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblRetenciones = new javax.swing.JLabel();
        lblImpGan = new javax.swing.JLabel();
        txtImpGan = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblPercepIva = new javax.swing.JLabel();
        txtPercepIva = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblIngBrutos = new javax.swing.JLabel();
        txtIngBrutos = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblMunicipal = new javax.swing.JLabel();
        txtMunicipal = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblClienteExcel = new javax.swing.JLabel();
        lblTipoExcel = new javax.swing.JLabel();
        lblComprasExcel = new javax.swing.JLabel();
        lblAñoExcel = new javax.swing.JLabel();
        txtAñoExcel = new javax.swing.JTextField();
        btnGenerarExcel = new javax.swing.JButton();
        cmbxListaClientes = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPaneAyuda = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libros de IVA Compras - Carga y exportación");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        lblDiaEmision.setText("Dia");

        txtDiaEmision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiaEmisionMouseClicked(evt);
            }
        });

        lblFechaEmision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaEmision.setText("FECHA DE EMISIÓN");

        lblMesEmision.setText("Mes");

        txtMesEmision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesEmisionMouseClicked(evt);
            }
        });

        lblAñoEmision.setText("Año");

        txtAñoEmision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAñoEmisionMouseClicked(evt);
            }
        });

        lblTipoNroComprobante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoNroComprobante.setText("TIPO Y NÚMERO DE COMPROBANTE");

        lblTipoComprobante.setText("Tipo");

        comboBoxTipoComprobante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Factura", "Nota de Crédito", "Nota de Débito", "Liquidación", "Resumen Bancario", "Otros" }));
        comboBoxTipoComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoComprobanteActionPerformed(evt);
            }
        });

        lblFiltroTipoComprobante.setText("Filtro");

        lblNroComprobante.setText("Número");

        txtNroComprobante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNroComprobanteMouseClicked(evt);
            }
        });

        lblComprador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComprador.setText("VENDEDOR");

        lblNombreVendedor.setText("Vendedor");

        txtNombreVendedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreVendedorMouseClicked(evt);
            }
        });

        lblCUITVendedor.setText("C.U.I.T.");

        txtCUITVendedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCUITVendedor.setText(" --------0--------");
        txtCUITVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCUITVendedorMouseClicked(evt);
            }
        });

        txtImporteTotIVA.setText("0");
        txtImporteTotIVA.setAutoscrolls(false);
        txtImporteTotIVA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtImporteTotIVAMouseClicked(evt);
            }
        });

        lblImporteTotIVA.setText("Importe");

        lblImporteTotcIVA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImporteTotcIVA.setText("IMPORTE TOTAL");

        lblConceptoImpNoNetoGravado.setText("Concepto");

        txtConceptoImpNoNetoGravado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConceptoImpNoNetoGravadoMouseClicked(evt);
            }
        });

        lblImporteNoNetoGravado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImporteNoNetoGravado.setText("IMPORTES QUE NO INTEGRAN EL PRECIO NETO GRAVADO");

        lblImporteImpNoNetoGravado.setText("Importe");

        txtImporteImpNoNetoGravado.setText("0");
        txtImporteImpNoNetoGravado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtImporteImpNoNetoGravadoMouseClicked(evt);
            }
        });

        lblRetenciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetenciones.setText("RETENCIONES");

        lblImpGan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImpGan.setText("Impuestos a las Ganancias");

        txtImpGan.setText("0");
        txtImpGan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtImpGanMouseClicked(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblPercepIva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPercepIva.setText("Percepciones de IVA");

        txtPercepIva.setText("0");
        txtPercepIva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPercepIvaMouseClicked(evt);
            }
        });

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblIngBrutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngBrutos.setText("Ingresos Brutos");

        txtIngBrutos.setText("0");
        txtIngBrutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIngBrutosMouseClicked(evt);
            }
        });

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblMunicipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMunicipal.setText("Municipal");

        txtMunicipal.setText("0");
        txtMunicipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMunicipalMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(439, 439, 439)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblImporteImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtImporteImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblConceptoImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtConceptoImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(411, 411, 411)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 402, Short.MAX_VALUE))
                    .addComponent(lblFechaEmision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtImpGan)
                            .addComponent(lblImpGan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPercepIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPercepIva, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIngBrutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIngBrutos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMunicipal)
                            .addComponent(lblMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDiaEmision)
                        .addGap(12, 12, 12)
                        .addComponent(txtDiaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMesEmision)
                        .addGap(12, 12, 12)
                        .addComponent(txtMesEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAñoEmision)
                        .addGap(12, 12, 12)
                        .addComponent(txtAñoEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(489, 489, 489))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreVendedor)
                            .addComponent(lblCUITVendedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCUITVendedor)
                            .addComponent(txtNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(lblImporteTotIVA)
                        .addGap(12, 12, 12)
                        .addComponent(txtImporteTotIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNroComprobante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNroComprobante))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTipoComprobante)
                                .addGap(12, 12, 12)
                                .addComponent(comboBoxTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblFiltroTipoComprobante)
                                .addGap(12, 12, 12)
                                .addComponent(comboBoxFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator8)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImporteTotcIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator13)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImporteNoNetoGravado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRetenciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipoNroComprobante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblComprador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addContainerGap())
                    .addComponent(jSeparator3)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblFechaEmision)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAñoEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiaEmision)
                            .addComponent(lblMesEmision)
                            .addComponent(lblAñoEmision))))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoNroComprobante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoComprobante)
                            .addComponent(lblFiltroTipoComprobante))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNroComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblNroComprobante)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComprador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblNombreVendedor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCUITVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCUITVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImporteTotcIVA)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblImporteTotIVA))
                    .addComponent(txtImporteTotIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImporteNoNetoGravado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConceptoImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConceptoImpNoNetoGravado))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImporteImpNoNetoGravado)
                    .addComponent(txtImporteImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblRetenciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImpGan)
                        .addGap(18, 18, 18)
                        .addComponent(txtImpGan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPercepIva)
                                .addComponent(lblIngBrutos)
                                .addComponent(lblMunicipal))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPercepIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIngBrutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator5)
                        .addComponent(jSeparator6)
                        .addComponent(jSeparator7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carga de Datos", jPanel1);

        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Mes", "Año", "Tipo Comp", "Num Comp", "Denominación", "C.U.I.T.", "Imp c/IVA", "Concepto que no int png", "Imp que no int png", "IVA 21%", "IVA 27%", "IVA 10,5%", "Neto 21%", "R. Imp Gcias", "R. Percep IVA", "R. Ing Brutos", "R. Mpal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCompras.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaCompras);
        tablaCompras.getColumnModel().getColumn(0).setPreferredWidth(35);
        tablaCompras.getColumnModel().getColumn(1).setPreferredWidth(40);
        tablaCompras.getColumnModel().getColumn(2).setPreferredWidth(47);
        tablaCompras.getColumnModel().getColumn(3).setPreferredWidth(90);
        tablaCompras.getColumnModel().getColumn(4).setPreferredWidth(110);
        tablaCompras.getColumnModel().getColumn(5).setPreferredWidth(120);
        tablaCompras.getColumnModel().getColumn(6).setPreferredWidth(80);
        tablaCompras.getColumnModel().getColumn(7).setPreferredWidth(90);
        tablaCompras.getColumnModel().getColumn(8).setPreferredWidth(100);
        tablaCompras.getColumnModel().getColumn(9).setPreferredWidth(100);
        tablaCompras.getColumnModel().getColumn(10).setPreferredWidth(80);
        tablaCompras.getColumnModel().getColumn(11).setPreferredWidth(80);
        tablaCompras.getColumnModel().getColumn(12).setPreferredWidth(80);
        tablaCompras.getColumnModel().getColumn(13).setPreferredWidth(80);
        tablaCompras.getColumnModel().getColumn(14).setPreferredWidth(50);
        tablaCompras.getColumnModel().getColumn(15).setPreferredWidth(50);
        tablaCompras.getColumnModel().getColumn(16).setPreferredWidth(50);
        tablaCompras.getColumnModel().getColumn(17).setPreferredWidth(50);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vista Preliminar", jPanel2);

        lblClienteExcel.setText("Proveedor:");

        lblTipoExcel.setText("Tipo de libro: ");

        lblComprasExcel.setText("Compras");

        lblAñoExcel.setText("Año:");

        btnGenerarExcel.setText("GENERAR ARCHIVO EXCEL");
        btnGenerarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(550, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGenerarExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClienteExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoExcel)
                            .addComponent(lblAñoExcel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAñoExcel)
                            .addComponent(lblComprasExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbxListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(435, 435, 435))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteExcel)
                    .addComponent(cmbxListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoExcel)
                    .addComponent(lblComprasExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAñoExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAñoExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerarExcel)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informe", jPanel3);

        txtPaneAyuda.setEditable(false);
        txtPaneAyuda.setContentType("text/html"); // NOI18N
        txtPaneAyuda.setText("");
        txtPaneAyuda.setToolTipText("");
        jScrollPane4.setViewportView(txtPaneAyuda);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ayuda", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImporteImpNoNetoGravadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImporteImpNoNetoGravadoMouseClicked
        txtImporteImpNoNetoGravado.setText("");
    }//GEN-LAST:event_txtImporteImpNoNetoGravadoMouseClicked

    private void txtConceptoImpNoNetoGravadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConceptoImpNoNetoGravadoMouseClicked
        txtConceptoImpNoNetoGravado.setText("");
    }//GEN-LAST:event_txtConceptoImpNoNetoGravadoMouseClicked

    private void txtImporteTotIVAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImporteTotIVAMouseClicked
        txtImporteTotIVA.setText("0-0");
    }//GEN-LAST:event_txtImporteTotIVAMouseClicked

    private void txtCUITVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCUITVendedorMouseClicked
        txtCUITVendedor.setText( "--------0--------");
    }//GEN-LAST:event_txtCUITVendedorMouseClicked

    private void txtNombreVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreVendedorMouseClicked
        txtNombreVendedor.setText("");
    }//GEN-LAST:event_txtNombreVendedorMouseClicked

    private void txtNroComprobanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNroComprobanteMouseClicked
        txtNroComprobante.setText("");
    }//GEN-LAST:event_txtNroComprobanteMouseClicked

    private void comboBoxTipoComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoComprobanteActionPerformed
//Cada vez que selecciono un valor del combobox se carga los distintos tipos de ese valor
        int tipo = comboBoxTipoComprobante.getSelectedIndex();
        String[] factura = {"A","B","C"};
        String[] notaDeCreditoDebito = {"A","B"};
        String [] modelNull = {""};
        if (tipo==0){
            comboBoxFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel(factura));
        }
        if (tipo==1 || tipo==2){
            comboBoxFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel(notaDeCreditoDebito));
        } if (tipo==3 || tipo==4 || tipo==5){
            comboBoxFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel(modelNull));
            comboBoxFiltroTipo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_comboBoxTipoComprobanteActionPerformed

    private void txtAñoEmisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAñoEmisionMouseClicked
        txtAñoEmision.setText("");
    }//GEN-LAST:event_txtAñoEmisionMouseClicked

    private void txtMesEmisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesEmisionMouseClicked
        txtMesEmision.setText("");
    }//GEN-LAST:event_txtMesEmisionMouseClicked

    private void txtDiaEmisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaEmisionMouseClicked
        txtDiaEmision.setText("");
    }//GEN-LAST:event_txtDiaEmisionMouseClicked

    private String reemplazarComas(String textoSinReemplazar){
//Metodo usado para reemplazar comas por puntos
        String textoReemplazado = textoSinReemplazar.replace(",",".");
        return textoReemplazado;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Metodo que instancia el objeto a partir de las variables ingresadas por el usuario
        String dia = txtDiaEmision.getText();
        String mes = txtMesEmision.getText();
        String año = txtAñoEmision.getText();
        String tipoComp = (String)comboBoxTipoComprobante.getSelectedItem()+" "+(String)comboBoxFiltroTipo.getSelectedItem();
        String numComp = txtNroComprobante.getText();
        String nomComprador = txtNombreVendedor.getText();
        String cuit = txtCUITVendedor.getText();
        String impIva = reemplazarComas(txtImporteTotIVA.getText());
        String conceptoFueraNeto = reemplazarComas(txtConceptoImpNoNetoGravado.getText());
        String importeFueraNeto = reemplazarComas(txtImporteImpNoNetoGravado.getText());
        String retenImpGcias = reemplazarComas(txtImpGan.getText());
        String retenPercepIva = reemplazarComas(txtPercepIva.getText());
        String retenIngBrutos = reemplazarComas(txtIngBrutos.getText());
        String retenMpal = reemplazarComas(txtMunicipal.getText());
        
        if ("".equals(dia)||"".equals(mes)||"".equals(año)||"".equals(numComp)||"".equals(nomComprador)||"".equals(cuit)
                ||"".equals(impIva)||"".equals(conceptoFueraNeto)||"".equals(importeFueraNeto)||"".equals(retenImpGcias)
                ||"".equals(retenPercepIva)||"".equals(retenIngBrutos)||"".equals(retenMpal)){
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar rellenos", "ERROR", 1);
        }else{
            Compra compra = new Compra(Integer.parseInt(dia), Integer.parseInt(mes), Integer.parseInt(año), Double.parseDouble(impIva)
                    , conceptoFueraNeto, Double.parseDouble(importeFueraNeto), Double.parseDouble(retenImpGcias)
                    , Double.parseDouble(retenPercepIva), Double.parseDouble(retenIngBrutos), Double.parseDouble(retenMpal), tipoComp
                    , numComp, nomComprador, cuit);
            
            compras.setCompras(compra);
            info.setCompras(compra);
            actualizarTabla(compra);
            contadorFilas++;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void actualizarTabla(Compra compra){
//Metodo que actualiza la tabla cada vez que se agrega una linea
        DefaultTableModel model = (DefaultTableModel) tablaCompras.getModel();
        model.addRow(new Object [] {"Dia", "Mes", "Año", "Tipo Comp", "Num Comp", "Denominación", "C.U.I.T.", "Imp c/IVA"
                , "Concepto que no int png", "Imp que no int png", "IVA 21%", "IVA 27%", "IVA 10,5%", "Neto 21%", "Reten Imp Gcias"
                , "Reten Percep IVA", "Reten Ing Brutos", "Reten Mpal"});
        tablaCompras.setValueAt(compra.getDia(), contadorFilas, 0);
        tablaCompras.setValueAt(compra.getMes(), contadorFilas, 1);
        tablaCompras.setValueAt(compra.getAño(), contadorFilas, 2);
        tablaCompras.setValueAt(compra.getTipoComp(), contadorFilas, 3);
        tablaCompras.setValueAt(compra.getNumComp(), contadorFilas, 4);
        tablaCompras.setValueAt(compra.getNomVendedor(), contadorFilas, 5);
        tablaCompras.setValueAt(compra.getCuitVendedor(), contadorFilas, 6);
        tablaCompras.setValueAt(compra.getImpIva(), contadorFilas, 7);
        tablaCompras.setValueAt(compra.getConceptoFueraNetoGravado(), contadorFilas, 8);
        tablaCompras.setValueAt(compra.getImpFueraNetoGravado(), contadorFilas, 9);
        tablaCompras.setValueAt(compra.getImpIva21(), contadorFilas, 10);
        tablaCompras.setValueAt(compra.getImpIva27(), contadorFilas, 11);
        tablaCompras.setValueAt(compra.getImpIva105(), contadorFilas, 12);
        tablaCompras.setValueAt(compra.getNetoGravado21(), contadorFilas, 13);
        tablaCompras.setValueAt(compra.getRetenImpGcias(), contadorFilas, 14);
        tablaCompras.setValueAt(compra.getRetenPercepIva(), contadorFilas, 15);
        tablaCompras.setValueAt(compra.getRetenIngBrutos(), contadorFilas, 16);
        tablaCompras.setValueAt(compra.getRetenMpal(), contadorFilas, 17);
    }
    private void btnGenerarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarExcelActionPerformed
        String nombre = (String) cmbxListaClientes.getSelectedItem();
        String año = txtAñoExcel.getText();
        try {
            info.buildExcel(contadorFilas,nombre,año);
        } catch (WriteException ex) {
            Logger.getLogger(VentanaCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarExcelActionPerformed

    private void txtImpGanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImpGanMouseClicked
        txtImpGan.setText("");
    }//GEN-LAST:event_txtImpGanMouseClicked

    private void txtPercepIvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPercepIvaMouseClicked
        txtPercepIva.setText("");
    }//GEN-LAST:event_txtPercepIvaMouseClicked

    private void txtIngBrutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIngBrutosMouseClicked
        txtIngBrutos.setText("");
    }//GEN-LAST:event_txtIngBrutosMouseClicked

    private void txtMunicipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMunicipalMouseClicked
        txtMunicipal.setText("");
    }//GEN-LAST:event_txtMunicipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaCompras().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarExcel;
    private javax.swing.JComboBox cmbxListaClientes;
    private javax.swing.JComboBox comboBoxFiltroTipo;
    private javax.swing.JComboBox comboBoxTipoComprobante;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAñoEmision;
    private javax.swing.JLabel lblAñoExcel;
    private javax.swing.JLabel lblCUITVendedor;
    private javax.swing.JLabel lblClienteExcel;
    private javax.swing.JLabel lblComprador;
    private javax.swing.JLabel lblComprasExcel;
    private javax.swing.JLabel lblConceptoImpNoNetoGravado;
    private javax.swing.JLabel lblDiaEmision;
    private javax.swing.JLabel lblFechaEmision;
    private javax.swing.JLabel lblFiltroTipoComprobante;
    private javax.swing.JLabel lblImpGan;
    private javax.swing.JLabel lblImporteImpNoNetoGravado;
    private javax.swing.JLabel lblImporteNoNetoGravado;
    private javax.swing.JLabel lblImporteTotIVA;
    private javax.swing.JLabel lblImporteTotcIVA;
    private javax.swing.JLabel lblIngBrutos;
    private javax.swing.JLabel lblMesEmision;
    private javax.swing.JLabel lblMunicipal;
    private javax.swing.JLabel lblNombreVendedor;
    private javax.swing.JLabel lblNroComprobante;
    private javax.swing.JLabel lblPercepIva;
    private javax.swing.JLabel lblRetenciones;
    private javax.swing.JLabel lblTipoComprobante;
    private javax.swing.JLabel lblTipoExcel;
    private javax.swing.JLabel lblTipoNroComprobante;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTextField txtAñoEmision;
    private javax.swing.JTextField txtAñoExcel;
    private javax.swing.JTextField txtCUITVendedor;
    private javax.swing.JTextField txtConceptoImpNoNetoGravado;
    private javax.swing.JTextField txtDiaEmision;
    private javax.swing.JTextField txtImpGan;
    private javax.swing.JTextField txtImporteImpNoNetoGravado;
    private javax.swing.JTextField txtImporteTotIVA;
    private javax.swing.JTextField txtIngBrutos;
    private javax.swing.JTextField txtMesEmision;
    private javax.swing.JTextField txtMunicipal;
    private javax.swing.JTextField txtNombreVendedor;
    private javax.swing.JTextField txtNroComprobante;
    private javax.swing.JTextPane txtPaneAyuda;
    private javax.swing.JTextField txtPercepIva;
    // End of variables declaration//GEN-END:variables
}
