/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package libros.de.iva;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.write.WriteException;

/**
 * @author Agus Venturi
 */
public class VentanaVentas extends javax.swing.JFrame {

    private ConjuntoVentas ventas = new ConjuntoVentas();
    private InformeVentas info = new InformeVentas();
    private int contadorFilas = 0;
    private int indiceListas;

    /**
     * Creates new form VentanaVentas
     */
    public VentanaVentas() {
        initComponents();
//Abro el arhivo de ayuda para cargarlo al TextPane
        File f = new File("Ayuda/Ayuda - Ventas.html");
        FileReader fr = null;
        try {
            fr = new FileReader(f);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaListaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br = new BufferedReader(fr);
        String st = "";
        try {
            int a = Txt.count(f);
            int b = 0;
            while (b != a) {
                a -= 1;
                st = st + br.readLine();
            }
            txtPaneAyuda.setText(st);
        } catch (IOException ex) {
            Logger.getLogger(VentanaListaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
//Abro la lista de clientes para cargarlos al combobox
        f = new File("ListaDeClientes.txt");
        fr = null;
        try {
            fr = new FileReader(f);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaListaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        br = new BufferedReader(fr);
        st = "";
        try {
            int a = Txt.count(f);
            int b = 0;
            while (b != a) {
                a -= 1;
                st = br.readLine();
                cmbxListaClientes.addItem(st);
            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaListaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCarga = new javax.swing.JPanel();
        lblFechaEmision = new javax.swing.JLabel();
        lblDiaEmision = new javax.swing.JLabel();
        txtDiaEmision = new javax.swing.JTextField();
        lblMesEmision = new javax.swing.JLabel();
        txtMesEmision = new javax.swing.JTextField();
        lblAñoEmision = new javax.swing.JLabel();
        txtAñoEmision = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTipoNroComprobante = new javax.swing.JLabel();
        lblTipoComprobante = new javax.swing.JLabel();
        comboBoxTipoComprobante = new javax.swing.JComboBox();
        lblFiltroTipoComprobante = new javax.swing.JLabel();
        comboBoxFiltroTipo = new javax.swing.JComboBox();
        lblNroComprobante = new javax.swing.JLabel();
        txtNroComprobante = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblComprador = new javax.swing.JLabel();
        lblNombreComprador = new javax.swing.JLabel();
        txtNombreComprador = new javax.swing.JTextField();
        lblCUITComprador = new javax.swing.JLabel();
        txtCUITComprador = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        lblImporteTotcIVA = new javax.swing.JLabel();
        lblImporteTotIVA = new javax.swing.JLabel();
        txtImporteTotIVA = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblImporteNoNetoGravado = new javax.swing.JLabel();
        lblConceptoImpNoNetoGravado = new javax.swing.JLabel();
        txtConceptoImpNoNetoGravado = new javax.swing.JTextField();
        lblImporteImpNoNetoGravado = new javax.swing.JLabel();
        txtImporteImpNoNetoGravado = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblPercepciones = new javax.swing.JLabel();
        txtPercepciones = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        panelVista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        panelInforme = new javax.swing.JPanel();
        btnGenerarExcel = new javax.swing.JButton();
        lblTipoExcel = new javax.swing.JLabel();
        lblClienteExcel = new javax.swing.JLabel();
        lblAñoExcel = new javax.swing.JLabel();
        txtAñoExcel = new javax.swing.JTextField();
        lblVentasExcel = new javax.swing.JLabel();
        cmbxListaClientes = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPaneAyuda = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Libros de IVA Ventas - Carga y exportación");

        jTabbedPane1.setToolTipText("");

        lblFechaEmision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaEmision.setText("FECHA DE EMISIÓN");

        lblDiaEmision.setText("Dia");

        txtDiaEmision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiaEmisionMouseClicked(evt);
            }
        });

        lblMesEmision.setText("Mes");

        txtMesEmision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesEmisionMouseClicked(evt);
            }
        });

        lblAñoEmision.setText("Año");

        txtAñoEmision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAñoEmisionMouseClicked(evt);
            }
        });

        lblTipoNroComprobante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoNroComprobante.setText("TIPO Y NÚMERO DE COMPROBANTE");

        lblTipoComprobante.setText("Tipo");

        comboBoxTipoComprobante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Factura", "Nota de Crédito", "Nota de Débito" }));
        comboBoxTipoComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoComprobanteActionPerformed(evt);
            }
        });

        lblFiltroTipoComprobante.setText("Filtro");

        lblNroComprobante.setText("Número");

        txtNroComprobante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNroComprobanteMouseClicked(evt);
            }
        });

        lblComprador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComprador.setText("COMPRADOR");

        lblNombreComprador.setText("Comprador");

        txtNombreComprador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreComprador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreCompradorMouseClicked(evt);
            }
        });

        lblCUITComprador.setText("C.U.I.T.");

        txtCUITComprador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCUITComprador.setText(" --------0--------");
        txtCUITComprador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCUITCompradorMouseClicked(evt);
            }
        });

        lblImporteTotcIVA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImporteTotcIVA.setText("IMPORTE TOTAL CON IVA (separar los valores con \"-\" | usar \",\" para decimales)");

        lblImporteTotIVA.setText("Importe");

        txtImporteTotIVA.setText("0-0");
        txtImporteTotIVA.setAutoscrolls(false);
        txtImporteTotIVA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtImporteTotIVAMouseClicked(evt);
            }
        });
        txtImporteTotIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporteTotIVAActionPerformed(evt);
            }
        });

        lblImporteNoNetoGravado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImporteNoNetoGravado.setText("IMPORTES QUE NO INTEGRAN EL PRECIO NETO GRAVADO");

        lblConceptoImpNoNetoGravado.setText("Concepto");

        txtConceptoImpNoNetoGravado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConceptoImpNoNetoGravadoMouseClicked(evt);
            }
        });

        lblImporteImpNoNetoGravado.setText("Importe");

        txtImporteImpNoNetoGravado.setText("0");
        txtImporteImpNoNetoGravado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtImporteImpNoNetoGravadoMouseClicked(evt);
            }
        });

        lblPercepciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPercepciones.setText("PERCEPCIONES");

        txtPercepciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPercepcionesMouseClicked(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCargaLayout = new javax.swing.GroupLayout(panelCarga);
        panelCarga.setLayout(panelCargaLayout);
        panelCargaLayout.setHorizontalGroup(
            panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                        .addComponent(lblImporteTotIVA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImporteTotIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(507, 507, 507))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                        .addComponent(lblDiaEmision)
                        .addGap(12, 12, 12)
                        .addComponent(txtDiaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMesEmision)
                        .addGap(12, 12, 12)
                        .addComponent(txtMesEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAñoEmision)
                        .addGap(12, 12, 12)
                        .addComponent(txtAñoEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(493, 493, 493))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCargaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaEmision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCargaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCargaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImporteNoNetoGravado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblComprador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCargaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoNroComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblImporteTotcIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPercepciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(panelCargaLayout.createSequentialGroup()
                .addGap(503, 503, 503)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCargaLayout.createSequentialGroup()
                            .addComponent(lblNroComprobante)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNroComprobante))
                        .addGroup(panelCargaLayout.createSequentialGroup()
                            .addComponent(lblTipoComprobante)
                            .addGap(12, 12, 12)
                            .addComponent(comboBoxTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(lblFiltroTipoComprobante)
                            .addGap(12, 12, 12)
                            .addComponent(comboBoxFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCargaLayout.createSequentialGroup()
                        .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreComprador)
                            .addComponent(lblCUITComprador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreComprador)
                            .addComponent(txtCUITComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCargaLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConceptoImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImporteImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtImporteImpNoNetoGravado)
                    .addComponent(txtConceptoImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                        .addComponent(txtPercepciones, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(397, 397, 397))))
        );
        panelCargaLayout.setVerticalGroup(
            panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblFechaEmision)
                .addGap(6, 6, 6)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAñoEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCargaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiaEmision)
                            .addComponent(lblMesEmision)
                            .addComponent(lblAñoEmision))))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblTipoNroComprobante)
                .addGap(6, 6, 6)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxFiltroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCargaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoComprobante)
                            .addComponent(lblFiltroTipoComprobante))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNroComprobante)
                    .addComponent(txtNroComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComprador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCargaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblNombreComprador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCUITComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCUITComprador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblImporteTotcIVA)
                .addGap(6, 6, 6)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImporteTotIVA)
                    .addComponent(txtImporteTotIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImporteNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConceptoImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConceptoImpNoNetoGravado))
                .addGap(4, 4, 4)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImporteImpNoNetoGravado)
                    .addComponent(txtImporteImpNoNetoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblPercepciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPercepciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carga de datos", panelCarga);

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Mes", "Año", "Tipo Comp", "Num Comp", "Denominación", "C.U.I.T.", "Imp c/IVA", "Concepto que no int PNG", "Importe que no int PNG", "IVA 21%", "Neto 21%", "Percepciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaVentas);
        tablaVentas.getColumnModel().getColumn(0).setPreferredWidth(35);
        tablaVentas.getColumnModel().getColumn(0).setMaxWidth(35);
        tablaVentas.getColumnModel().getColumn(1).setPreferredWidth(40);
        tablaVentas.getColumnModel().getColumn(1).setMaxWidth(40);
        tablaVentas.getColumnModel().getColumn(2).setPreferredWidth(47);
        tablaVentas.getColumnModel().getColumn(2).setMaxWidth(47);
        tablaVentas.getColumnModel().getColumn(3).setPreferredWidth(140);
        tablaVentas.getColumnModel().getColumn(3).setMaxWidth(140);
        tablaVentas.getColumnModel().getColumn(4).setPreferredWidth(145);
        tablaVentas.getColumnModel().getColumn(4).setMaxWidth(145);
        tablaVentas.getColumnModel().getColumn(5).setMinWidth(220);
        tablaVentas.getColumnModel().getColumn(5).setPreferredWidth(220);
        tablaVentas.getColumnModel().getColumn(5).setMaxWidth(220);
        tablaVentas.getColumnModel().getColumn(6).setPreferredWidth(120);
        tablaVentas.getColumnModel().getColumn(6).setMaxWidth(120);
        tablaVentas.getColumnModel().getColumn(7).setPreferredWidth(85);
        tablaVentas.getColumnModel().getColumn(7).setMaxWidth(85);
        tablaVentas.getColumnModel().getColumn(8).setMinWidth(70);
        tablaVentas.getColumnModel().getColumn(8).setPreferredWidth(70);
        tablaVentas.getColumnModel().getColumn(9).setMinWidth(70);
        tablaVentas.getColumnModel().getColumn(9).setPreferredWidth(70);
        tablaVentas.getColumnModel().getColumn(10).setPreferredWidth(75);
        tablaVentas.getColumnModel().getColumn(10).setMaxWidth(75);
        tablaVentas.getColumnModel().getColumn(11).setPreferredWidth(85);
        tablaVentas.getColumnModel().getColumn(11).setMaxWidth(85);
        tablaVentas.getColumnModel().getColumn(12).setPreferredWidth(90);

        javax.swing.GroupLayout panelVistaLayout = new javax.swing.GroupLayout(panelVista);
        panelVista.setLayout(panelVistaLayout);
        panelVistaLayout.setHorizontalGroup(
            panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1277, Short.MAX_VALUE)
        );
        panelVistaLayout.setVerticalGroup(
            panelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vista Preliminar", panelVista);

        btnGenerarExcel.setText("GENERAR ARCHIVO EXCEL");
        btnGenerarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarExcelActionPerformed(evt);
            }
        });

        lblTipoExcel.setText("Tipo de libro: ");

        lblClienteExcel.setText("Cliente:");

        lblAñoExcel.setText("Año:");

        lblVentasExcel.setText("Ventas");

        javax.swing.GroupLayout panelInformeLayout = new javax.swing.GroupLayout(panelInforme);
        panelInforme.setLayout(panelInformeLayout);
        panelInformeLayout.setHorizontalGroup(
            panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformeLayout.createSequentialGroup()
                .addGap(499, 499, 499)
                .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGenerarExcel, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addGroup(panelInformeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClienteExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelInformeLayout.createSequentialGroup()
                                .addComponent(lblTipoExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addGroup(panelInformeLayout.createSequentialGroup()
                                .addComponent(lblAñoExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(70, 70, 70)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAñoExcel)
                            .addComponent(lblVentasExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbxListaClientes, 0, 219, Short.MAX_VALUE))))
                .addGap(450, 450, 450))
        );
        panelInformeLayout.setVerticalGroup(
            panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformeLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteExcel)
                    .addComponent(cmbxListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoExcel)
                    .addComponent(lblVentasExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAñoExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAñoExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerarExcel)
                .addGap(200, 200, 200))
        );

        jTabbedPane1.addTab("Informe", panelInforme);

        txtPaneAyuda.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(txtPaneAyuda);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1257, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ayuda", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String reemplazarComas(String textoSinReemplazar) {
//Metodo para reemplazar comas por puntos
        String textoReemplazado = textoSinReemplazar.replace(",", ".");
        return textoReemplazado;
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
//Aca instancio el objeto Venta a partir de las variables ingresadas por el usuario
        String dia = txtDiaEmision.getText();
        String mes = txtMesEmision.getText();
        String año = txtAñoEmision.getText();
        String tipoCompP1 = "";
        tipoCompP1 = (String) comboBoxTipoComprobante.getSelectedItem();
        String tipoCompP2 = "";
        tipoCompP2 = (String) comboBoxFiltroTipo.getSelectedItem();
        String tipoComp = tipoCompP1 + " " + tipoCompP2;
        String numComp = txtNroComprobante.getText();
        String nomComprador = txtNombreComprador.getText();
        String cuit = txtCUITComprador.getText();
        String[] impIvaSeparado = txtImporteTotIVA.getText().split("-");
        double impIvaDouble = 0;
        for (int i = 0; i < impIvaSeparado.length; i++) {
            String remplaComas = reemplazarComas(impIvaSeparado[i]);
            impIvaDouble += Double.parseDouble(remplaComas);
        }
        String impIva = reemplazarComas(txtImporteTotIVA.getText());
        String conceptoFueraNeto = reemplazarComas(txtConceptoImpNoNetoGravado.getText());
        String importeFueraNeto = reemplazarComas(txtImporteImpNoNetoGravado.getText());
        String percepciones = txtPercepciones.getText();

        if ("".equals(dia) || "".equals(mes) || "".equals(año) || "".equals(tipoComp) || "".equals(numComp) || "".equals(nomComprador)
                || "".equals(cuit) || "".equals(impIva) || "".equals(conceptoFueraNeto) || "".equals(importeFueraNeto) || "".equals(percepciones)) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar rellenos", "ERROR", 1);
        } else {
            Venta venta = new Venta(Integer.parseInt(dia), Integer.parseInt(mes), Integer.parseInt(año), contadorFilas, impIvaDouble, conceptoFueraNeto, Double.parseDouble(importeFueraNeto), tipoComp, numComp, nomComprador, cuit, percepciones);

            ventas.setVentas(venta);
            info.setVentas(venta);
            contadorFilas++;
            actualizarTabla(venta);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void actualizarTabla(Venta venta) {
//Metodo que actualiza la tabla cada vez que se agrega una linea
        DefaultTableModel model = (DefaultTableModel) tablaVentas.getModel();
        model.addRow(new Object[]{"Dia", "Mes", "Año", "Tipo Comp", "Num Comp", "Denominación", "C.U.I.T.", "Imp c/IVA", "Concepto que no int PNG", "Imp que no int PNG", "IVA 21%", "Neto 21%", "Percepciones"});
        tablaVentas.setValueAt(venta.getDia(), contadorFilas - 1, 0);
        tablaVentas.setValueAt(venta.getMes(), contadorFilas - 1, 1);
        tablaVentas.setValueAt(venta.getAño(), contadorFilas - 1, 2);
        tablaVentas.setValueAt(venta.getTipoComp(), contadorFilas - 1, 3);
        tablaVentas.setValueAt(venta.getNumComp(), contadorFilas - 1, 4);
        tablaVentas.setValueAt(venta.getNomComprador(), contadorFilas - 1, 5);
        tablaVentas.setValueAt(venta.getCuitComprador(), contadorFilas - 1, 6);
        tablaVentas.setValueAt(venta.getImpIva(), contadorFilas - 1, 7);
        tablaVentas.setValueAt(venta.getConceptoFueraNetoGravado(), contadorFilas - 1, 8);
        tablaVentas.setValueAt(venta.getImpFueraNetoGravado(), contadorFilas - 1, 9);
        tablaVentas.setValueAt(venta.getImpIvaFacturado(), contadorFilas - 1, 10);
        tablaVentas.setValueAt(venta.getNetoGravado(), contadorFilas - 1, 11);
        tablaVentas.setValueAt(venta.getPercepciones(), contadorFilas - 1, 12);
    }

    private void txtImporteTotIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporteTotIVAActionPerformed
        txtImporteTotIVA.setText("0-0");
    }//GEN-LAST:event_txtImporteTotIVAActionPerformed

    private void txtDiaEmisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaEmisionMouseClicked
        txtDiaEmision.setText("");
    }//GEN-LAST:event_txtDiaEmisionMouseClicked

    private void txtAñoEmisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAñoEmisionMouseClicked
        txtAñoEmision.setText("");
    }//GEN-LAST:event_txtAñoEmisionMouseClicked

    private void txtNroComprobanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNroComprobanteMouseClicked
        txtNroComprobante.setText("");
    }//GEN-LAST:event_txtNroComprobanteMouseClicked

    private void txtNombreCompradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreCompradorMouseClicked
        txtNombreComprador.setText("");
    }//GEN-LAST:event_txtNombreCompradorMouseClicked

    private void txtCUITCompradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCUITCompradorMouseClicked
        txtCUITComprador.setText("--------0--------");
    }//GEN-LAST:event_txtCUITCompradorMouseClicked

    private void txtImporteTotIVAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImporteTotIVAMouseClicked
        txtImporteTotIVA.setText("0-0");
    }//GEN-LAST:event_txtImporteTotIVAMouseClicked

    private void txtConceptoImpNoNetoGravadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConceptoImpNoNetoGravadoMouseClicked
        txtConceptoImpNoNetoGravado.setText("");
    }//GEN-LAST:event_txtConceptoImpNoNetoGravadoMouseClicked

    private void txtImporteImpNoNetoGravadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImporteImpNoNetoGravadoMouseClicked
        txtImporteImpNoNetoGravado.setText("");
    }//GEN-LAST:event_txtImporteImpNoNetoGravadoMouseClicked

    private void txtPercepcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPercepcionesMouseClicked
        txtPercepciones.setText("");
    }//GEN-LAST:event_txtPercepcionesMouseClicked

    private void comboBoxTipoComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoComprobanteActionPerformed
        int tipo = comboBoxTipoComprobante.getSelectedIndex();
        String[] factura = {"A", "B", "C"};
        String[] notaDeCreditoDebito = {"A", "B"};
        if (tipo == 0) {
            comboBoxFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel(factura));
        }
        if (tipo == 1) {
            comboBoxFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel(notaDeCreditoDebito));
        }
        if (tipo == 2) {
            comboBoxFiltroTipo.setModel(new javax.swing.DefaultComboBoxModel(notaDeCreditoDebito));
        }
    }//GEN-LAST:event_comboBoxTipoComprobanteActionPerformed

    private void txtMesEmisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesEmisionMouseClicked
        txtMesEmision.setText("");
    }//GEN-LAST:event_txtMesEmisionMouseClicked

    private void btnGenerarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarExcelActionPerformed
        String nombre = (String) cmbxListaClientes.getSelectedItem();
        String año = txtAñoExcel.getText();
        try {
            info.buildExcel(contadorFilas, nombre, año);
        } catch (WriteException ex) {
            Logger.getLogger(VentanaVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGenerarExcel;
    private javax.swing.JComboBox cmbxListaClientes;
    private javax.swing.JComboBox comboBoxFiltroTipo;
    private javax.swing.JComboBox comboBoxTipoComprobante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAñoEmision;
    private javax.swing.JLabel lblAñoExcel;
    private javax.swing.JLabel lblCUITComprador;
    private javax.swing.JLabel lblClienteExcel;
    private javax.swing.JLabel lblComprador;
    private javax.swing.JLabel lblConceptoImpNoNetoGravado;
    private javax.swing.JLabel lblDiaEmision;
    private javax.swing.JLabel lblFechaEmision;
    private javax.swing.JLabel lblFiltroTipoComprobante;
    private javax.swing.JLabel lblImporteImpNoNetoGravado;
    private javax.swing.JLabel lblImporteNoNetoGravado;
    private javax.swing.JLabel lblImporteTotIVA;
    private javax.swing.JLabel lblImporteTotcIVA;
    private javax.swing.JLabel lblMesEmision;
    private javax.swing.JLabel lblNombreComprador;
    private javax.swing.JLabel lblNroComprobante;
    private javax.swing.JLabel lblPercepciones;
    private javax.swing.JLabel lblTipoComprobante;
    private javax.swing.JLabel lblTipoExcel;
    private javax.swing.JLabel lblTipoNroComprobante;
    private javax.swing.JLabel lblVentasExcel;
    private javax.swing.JPanel panelCarga;
    private javax.swing.JPanel panelInforme;
    private javax.swing.JPanel panelVista;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtAñoEmision;
    private javax.swing.JTextField txtAñoExcel;
    private javax.swing.JTextField txtCUITComprador;
    private javax.swing.JTextField txtConceptoImpNoNetoGravado;
    private javax.swing.JTextField txtDiaEmision;
    private javax.swing.JTextField txtImporteImpNoNetoGravado;
    private javax.swing.JTextField txtImporteTotIVA;
    private javax.swing.JTextField txtMesEmision;
    private javax.swing.JTextField txtNombreComprador;
    private javax.swing.JTextField txtNroComprobante;
    private javax.swing.JTextPane txtPaneAyuda;
    private javax.swing.JTextField txtPercepciones;
    // End of variables declaration//GEN-END:variables
}